'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const repo=path.resolve(__dirname,'..');
function environment() {
  const timers=new Map();let serial=0;
  function node(tag,attrs={}) {
    let text=''; const n={tag,attrs:{...attrs},children:[],style:{},dataset:{},listeners:{},value:'',clientWidth:640,clientHeight:440,hidden:false,
      classList:{values:new Set(),add(...xs){xs.forEach(x=>this.values.add(x));},remove(...xs){xs.forEach(x=>this.values.delete(x));},toggle(x,on){if(on)this.add(x);else this.remove(x);}},
      setAttribute(k,v){this.attrs[k]=String(v);},getAttribute(k){return this.attrs[k];},
      appendChild(c){if(c.parentNode)c.parentNode.removeChild(c);this.children.push(c);c.parentNode=this;return c;},
      insertBefore(c,b){if(c.parentNode)c.parentNode.removeChild(c);const i=this.children.indexOf(b);this.children.splice(i<0?this.children.length:i,0,c);c.parentNode=this;return c;},
      removeChild(c){this.children=this.children.filter(x=>x!==c);c.parentNode=null;},remove(){this.parentNode?.removeChild(this);},
      addEventListener(k,f){(this.listeners[k]??=[]).push(f);},removeEventListener(k,f){this.listeners[k]=(this.listeners[k]||[]).filter(x=>x!==f);},
      emit(k,v={}){for(const f of [...this.listeners[k]||[]])f({preventDefault(){},stopPropagation(){},...v});},
      setPointerCapture(id){this.captured=id;},releasePointerCapture(id){if(this.captured===id)this.captured=null;},hasPointerCapture(id){return this.captured===id;},
      getBoundingClientRect(){return {left:0,top:0,width:640,height:440};},focus(){doc.activeElement=this;},
      querySelectorAll(sel){return walk(this).filter(x=>sel.startsWith('.')?x.className?.split(' ').includes(sel.slice(1)):x.tag===sel);}};
    Object.defineProperties(n,{textContent:{get(){return text;},set(v){text=String(v);}},firstChild:{get(){return this.children[0]||null;}},nextSibling:{get(){const a=this.parentNode?.children||[];return a[a.indexOf(this)+1]||null;}},innerHTML:{set(){this.children.forEach(x=>x.parentNode=null);this.children=[];}}});return n;
  }
  const doc={createElement:node},win=node('window');win.matchMedia=()=>({matches:true});win.requestAnimationFrame=()=>1;win.cancelAnimationFrame=()=>{};
  win.Sim2Transform={makeTransform(){return {toScreen:p=>({...p}),toWorld:p=>({...p}),scale:1};}};
  win.Sim2SvgRender={el:node,createSvg:()=>node('svg')};win.Sim2Overlay={createOverlay(){return {resize(){},reflow(){},dispose(){}};}};
  win.Sim2AnimationClock=require('../js/sim2/core/animation-clock');
  const ctx=vm.createContext({window:win,document:doc,console,Promise,Map,Set,Date,setTimeout:f=>{timers.set(++serial,f);return serial;},clearTimeout:id=>timers.delete(id)});
  for(const p of ['controls','panel','sim-shell'])vm.runInContext(fs.readFileSync(path.join(repo,'js/sim2/core',p+'.js'),'utf8'),ctx);
  return {win,doc,node,timers,ctx};
}
const walk=n=>[n,...n.children.flatMap(walk)];
function shell(e){return e.win.Sim2Shell.createSimShell({container:e.node('container'),worldBox:{minX:-5,maxX:5,minY:-5,maxY:5}});}
test('scalar keyboard maps physical value independent of handle coordinates',()=>{const e=environment(),s=shell(e);let value=2;const h=s.addHandle({x:0,y:2},{a11y:{axis:'x',min:1,max:6,step:.5,valueFromPoint:p=>p.y,pointFromValue:v=>({x:0,y:v}),valueText:p=>`${p.y} m`},onDrag:p=>value=p.y});h.node.emit('keydown',{key:'Home'});assert.equal(value,1);h.node.emit('keydown',{key:'End'});assert.equal(value,6);h.node.emit('keydown',{key:'ArrowLeft'});assert.equal(value,5.5);s.dispose();});
test('both drag APIs track pointer identity and cancel/lost capture end active drag once',()=>{const e=environment(),s=shell(e);let phases=[];const h=s.addHandle({x:0,y:0},{onDrag:(_,p)=>phases.push(p)});h.node.emit('pointerdown',{pointerId:1,button:0});e.win.emit('pointermove',{pointerId:2,clientX:20,clientY:30});assert.deepEqual(phases,['start']);e.win.emit('pointercancel',{pointerId:1});e.win.emit('pointermove',{pointerId:1,clientX:20,clientY:30});h.node.emit('lostpointercapture',{pointerId:1});assert.deepEqual(phases,['start','cancel']);phases=[];s.onPointerDrag((_,p)=>phases.push(p));s.svg.emit('pointerdown',{pointerId:3,button:0,clientX:1,clientY:2});s.svg.emit('pointermove',{pointerId:4,clientX:3,clientY:4});s.svg.emit('lostpointercapture',{pointerId:3});s.svg.emit('pointermove',{pointerId:3,clientX:3,clientY:4});assert.deepEqual(phases,['start','cancel']);s.dispose();});
test('readout preserves keyed DOM nodes and only announces on explicit user request',()=>{const e=environment(),p=e.win.Sim2Panel.createPanel(e.node('host'),{});p.setReadout([{key:'v',label:'Vận tốc',value:'3 m/s'}]);const first=walk(p.root).find(n=>n.attrs['data-readout-key']==='v');p.setReadout([{key:'v',label:'Vận tốc',value:'4 m/s'}]);assert.equal(walk(p.root).find(n=>n.attrs['data-readout-key']==='v'),first);const status=walk(p.root).find(n=>n.attrs.role==='status');assert.equal(status.textContent,'');const b=walk(p.root).find(n=>n.tag==='button');b.emit('click');assert.match(status.textContent,/Vận tốc: 4 m\/s/);p.dispose();});
test('controls validate numeric edits, preserve empty drafts, share slider value and dispose callbacks',()=>{const e=environment(),seen=[],c=e.win.Sim2Controls.createControls(e.node('host'),{sliders:[{id:'x',label:'x',min:1,max:6,step:.5,value:3,unit:'m',onInput:v=>seen.push(v)}],actions:[{id:'go',label:'Đến mốc',onClick:()=>seen.push('go')}]});const input=walk(c.root).find(n=>n.type==='number');assert.ok(input);input.value='';input.emit('input');assert.deepEqual(seen,[]);input.value='999';input.emit('change');assert.equal(seen.at(-1),6);c.setValue('x',4.5);assert.equal(+input.value,4.5);const button=walk(c.root).find(n=>n.attrs['data-action']==='go');button.emit('click');assert.equal(seen.at(-1),'go');c.setActionLabel('go','Tiếp theo');assert.equal(button.textContent,'Tiếp theo');c.dispose();button.emit('click');assert.equal(seen.length,2);});
test('standalone numeric/action controls survive viewport hiding and shell cleanup',()=>{const e=environment(),s=shell(e);let v=0;const c=s.addNumberControl({id:'d',label:'d',min:1,max:6,step:1,value:3,onInput:x=>v=x});const b=s.addAction({id:'reset',label:'Đặt lại',onClick:()=>v=3});c.setValue(4);s.root.style.display='none';assert.notEqual(b.parentNode,s.root);b.emit('click');assert.equal(v,3);s.dispose();b.emit('click');assert.equal(v,3);});
test('event seek binds exact physical time and clears accumulated wall time',()=>{const e=environment(),s=shell(e);s.onFrame(()=>{},()=>{});s.seekTime(1.75);assert.equal(s.getSimulationTime(),1.75);s.stepOnce();assert.ok(Math.abs(s.getSimulationTime()-(1.75+1/60))<1e-12);assert.throws(()=>s.seekTime(-1));s.dispose();});
test('2D/3D bridge snapshots nested physical state against caller mutation',()=>{const e=environment();vm.runInContext(fs.readFileSync(path.join(repo,'js/sim3/core/mode-toggle.js'),'utf8'),e.ctx);const container=e.node('div'),scene=e.node('div'),received=[];container.appendChild(scene);const bridge=e.win.Sim3Mode.attach({container,shell2dRoot:scene,create3d:()=>({setState:s=>received.push(s),resize(){},dispose(){}})});const state={t:1,point:{x:3,y:4}};bridge.setState(state);state.point.x=999;walk(container).find(n=>n.dataset.mode==='3d').emit('click');assert.equal(received.at(-1).point.x,3);assert.ok(Object.isFrozen(received.at(-1).point));bridge.dispose();});

test('meaningful event announcements are explicit and never frame-driven',()=>{const e=environment(),p=e.win.Sim2Panel.createPanel(e.node('host'),{});p.announce('Đã va chạm; mô phỏng tạm dừng');const status=walk(p.root).find(n=>n.attrs.role==='status');assert.match(status.textContent,/Đã va chạm/);p.setReadout([{key:'t',label:'t',value:'1.75 s'}]);assert.match(status.textContent,/Đã va chạm/);p.dispose();});

test('programmatic pause/play keeps shared playback button truthful',()=>{const e=environment(),s=shell(e);const c=s.addControls({playback:{playing:false,onPlay:()=>s.start(),onPause:()=>s.stop()}});const b=walk(c.root).find(n=>n.className==='sim2-playpause');s.start();assert.equal(b.attrs['aria-label'],'Tạm dừng');s.stop();assert.equal(b.attrs['aria-label'],'Chạy');s.dispose();});

test('numeric input colors reference existing theme tokens in light and dark mode',()=>{const css=fs.readFileSync(path.join(repo,'css/style.css'),'utf8');const rule=css.match(/\.sim2-number-input \{([^}]+)\}/)[1];assert.match(rule,/color:\s*var\(--tx\)/);assert.match(rule,/background:\s*var\(--bg\)/);assert.doesNotMatch(rule,/--bg-color/);});

test('number typing preserves fractional drafts until explicit change commit',()=>{const e=environment(),seen=[],c=e.win.Sim2Controls.createControls(e.node('host'),{sliders:[{id:'x',label:'x',min:0,max:6,step:.1,value:3,onInput:v=>seen.push(v)}]});const n=walk(c.root).find(n=>n.type==='number');n.value='1.';n.emit('input');assert.equal(n.value,'1.');assert.deepEqual(seen,[]);n.value='1.55';n.emit('input');assert.deepEqual(seen,[]);n.emit('keydown',{key:'Enter'});assert.deepEqual(seen,[1.55]);n.emit('change');assert.deepEqual(seen,[1.55]);c.dispose();});

test('native controls can represent exact decimals while explicit range/key step remains meaningful',()=>{const e=environment(),seen=[],c=e.win.Sim2Controls.createControls(e.node('host'),{sliders:[{id:'r',label:'r',min:.8,max:3.5,step:.1,value:1.55,onInput:v=>seen.push(v)}]});const r=walk(c.root).find(n=>n.type==='range'),n=walk(c.root).find(n=>n.type==='number');assert.equal(r.step,'any');assert.equal(n.step,'any');assert.equal(r.attrs['data-physical-step'],'0.1');c.setValue('r',1.55);assert.equal(+r.value,1.55);assert.equal(+n.value,1.55);r.emit('keydown',{key:'ArrowRight'});assert.ok(Math.abs(seen.at(-1)-1.65)<1e-12);n.emit('keydown',{key:'ArrowDown'});assert.ok(Math.abs(seen.at(-1)-1.55)<1e-12);r.value='1.57';r.emit('input');assert.ok(Math.abs(seen.at(-1)-1.6)<1e-12);c.dispose();});
