"""
Bundle all HTML fragments into a single JS file (js/pages.js).
This eliminates the need for an HTTP server — the app works via file:// protocol.

Usage: python tools/bundle_pages.py
"""
import os, json, glob

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CHAPTERS_DIR = os.path.join(ROOT, 'chapters')
DATA_DIR = os.path.join(ROOT, 'data')
OUTPUT = os.path.join(ROOT, 'js', 'pages.js')

def read_file(path):
    for enc in ('utf-8', 'utf-8-sig', 'cp1252', 'latin-1'):
        try:
            with open(path, 'r', encoding=enc) as f:
                return f.read()
        except (UnicodeDecodeError, UnicodeError):
            continue
    return ''

def build_page_map():
    """Read loader.js to extract PAGE_MAP keys and paths."""
    loader_path = os.path.join(ROOT, 'js', 'loader.js')
    content = read_file(loader_path)
    
    pages = {}
    import re
    # Match: 'key': 'path'
    for m in re.finditer(r"'([^']+)'\s*:\s*'([^']+\.html)'", content):
        key, path = m.group(1), m.group(2)
        full_path = os.path.join(ROOT, path.replace('/', os.sep))
        if os.path.exists(full_path):
            html = read_file(full_path)
            if html.strip():
                pages[key] = html
    return pages

def build_quiz_data():
    """Bundle quiz JSON files."""
    quizzes = {}
    for f in glob.glob(os.path.join(DATA_DIR, 'quiz-*.json')):
        basename = os.path.basename(f)
        data = read_file(f)
        if data.strip():
            quizzes[basename] = data.strip()
    return quizzes

def main():
    print("Bundling HTML fragments...")
    pages = build_page_map()
    print(f"  Found {len(pages)} pages")
    
    print("Bundling quiz data...")
    quizzes = build_quiz_data()
    print(f"  Found {len(quizzes)} quiz files")
    
    # Generate JS
    js_lines = ['// Auto-generated bundle — DO NOT EDIT MANUALLY']
    js_lines.append('// Generated by tools/bundle_pages.py')
    js_lines.append(f'// Total pages: {len(pages)}, Quiz files: {len(quizzes)}')
    js_lines.append('')
    
    # Pages bundle
    js_lines.append('const PAGES = {};')
    for key, html in sorted(pages.items()):
        escaped = json.dumps(html, ensure_ascii=False)
        js_lines.append(f'PAGES[{json.dumps(key)}] = {escaped};')
    
    js_lines.append('')
    
    # Quiz data bundle
    js_lines.append('const QUIZ_DATA = {};')
    for name, data in sorted(quizzes.items()):
        js_lines.append(f'QUIZ_DATA[{json.dumps(name)}] = {data};')
    
    # Write output
    output = '\n'.join(js_lines) + '\n'
    with open(OUTPUT, 'w', encoding='utf-8') as f:
        f.write(output)
    
    size_kb = len(output.encode('utf-8')) / 1024
    print(f"Output: {OUTPUT}")
    print(f"Size: {size_kb:.1f} KB")
    print("Done!")

if __name__ == '__main__':
    main()
