"""Bundle required HTML fragments and quiz data for offline ``file://`` use."""
import json
import os
from glob import glob

from content_manifest_utils import normalize_logical_path, read_text, repo_path

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(ROOT, "data")
OUTPUT = os.path.join(ROOT, "js", "pages.js")


def page_map():
    """Read PAGE_MAP while retaining every declared route for strict checks."""
    from content_manifest_utils import parse_page_map
    return parse_page_map(read_text(os.path.join(ROOT, "js", "loader.js")))


def build_page_map():
    pages = {}
    for route_id, logical_path in page_map().items():
        if logical_path is None:
            continue
        try:
            target = repo_path(ROOT, normalize_logical_path(logical_path))
        except ValueError as exc:
            raise SystemExit(f"PAGE_MAP route {route_id}: {exc}") from exc
        if not os.path.isfile(target):
            raise SystemExit(f"PAGE_MAP route {route_id}: missing required fragment {logical_path}")
        html = read_text(target)
        if not html.strip():
            raise SystemExit(f"PAGE_MAP route {route_id}: blank required fragment {logical_path}")
        pages[route_id] = html
    return pages


def build_quiz_data():
    quizzes = {}
    for filename in glob(os.path.join(DATA_DIR, "quiz-*.json")):
        data = read_text(filename).strip()
        if data:
            quizzes[os.path.basename(filename)] = data
    return quizzes


def main():
    print("Bundling HTML fragments...")
    pages = build_page_map()
    print(f"  Found {len(pages)} pages")
    print("Bundling quiz data...")
    quizzes = build_quiz_data()
    print(f"  Found {len(quizzes)} quiz files")
    lines = [
        "// Auto-generated bundle — DO NOT EDIT MANUALLY",
        "// Generated by tools/bundle_pages.py",
        f"// Total pages: {len(pages)}, Quiz files: {len(quizzes)}",
        "",
        "const PAGES = {};",
    ]
    lines.extend(f"PAGES[{json.dumps(key)}] = {json.dumps(value, ensure_ascii=False)};" for key, value in sorted(pages.items()))
    lines.extend(["", "const QUIZ_DATA = {};"])
    lines.extend(f"QUIZ_DATA[{json.dumps(key)}] = {value};" for key, value in sorted(quizzes.items()))
    output = "\n".join(lines) + "\n"
    with open(OUTPUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(output)
    print(f"Output: {OUTPUT}")
    print(f"Size: {len(output.encode('utf-8')) / 1024:.1f} KB")
    print("Done!")

if __name__ == '__main__':
    main()
